# Generated by Django 5.0.3 on 2024-03-04 20:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of menu item', max_length=255, unique=True)),
                ('url', models.CharField(default='menu/', max_length=255)),
                ('left', models.IntegerField(blank=True, null=True)),
                ('right', models.IntegerField(blank=True, null=True)),
                ('level', models.IntegerField(blank=True, null=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='main_app.menu')),
                ('root', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='head', to='main_app.menu')),
            ],
        ),
        migrations.DeleteModel(
            name='CustomMenu',
        ),
    ]
